### ISSUE TITLE
PhasorNet widespread adoption and distribution

### ISSUE THREAD

**Issue by Mariochem92** [ayleray/PhasorNet#3]
Hello everyone, have you thought of writing this code in python and/or come up with a python library? I think it would boost the distribution of your algorithm as per se it would be very useful!

**Comment by kuaikuaiby** [comment]
Hello，may I ask if you have run through the programme? I get an error in the run-through: subscript index must be subscript index must be positive integer type or logical type. I confirm that the version of matlab I am using is fine. Thank you very much if you can get back to me.

**Comment by ayleray** [comment]
The error is probably due to the fact that the format of the input file that you have selected is not correct. Could you please tell me the name of the file that you use ?

**Comment by kuaikuaiby** [comment]
I'm using the file you provided, without changing the filename( PhasorNet0 and TestSamples), and running it in train.exe is fine, but calcul.exe reports this error.

**Comment by ayleray** [comment]
I have updated the file. Please tell me if the problem is solved.

**Comment by kuaikuaiby** [comment]
No, it's the same error.

**Comment by ayleray** [comment]
I have solved the issue. Please upload this updated file.

**Comment by kuaikuaiby** [comment]
I am very sorry for not getting back to you in time due to jet lag, the issue has been resolved and it is crucial for my thesis work. Thank you again.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ayleray/PhasorNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月21日(星期四) 晚上9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ayleray/PhasorNet] PhasorNet widespread adoption and distribution (Issue #3)





 
I have solved the issue. Please upload this updated file.
